### ISSUE TITLE
'Please Wait' When Video Playback set to Show Information first

### ISSUE THREAD

**Issue by kaigame** [bigretromike/nakamori#228]
Bit of a weird one, left a post on discord too. After doing a bit of troubleshooting, i have found that if Kodi is set to show information prior to playback of the video file, you will get a Please Wait message stuck across the screen, the video is dimmed and an error is generated after playback. This behavior only happens through the nakamori plugin.

Note: This doesn't always happen on the very first video being played.

I have also included my log file for reference.
[kodi.log](https://github.com/bigretromike/nakamori/files/1597765/kodi.log)

**Comment by da3dsoul** [comment]
This sounds like a Kodi bug. I'd need to look into it further. If you have it set to play instead, it doesn't happen

**Comment by bigretromike** [comment]
The interesting part.
What is expected behavior for "show information" prior playback ? same as "info" ?

```
12:45:48.726 T:8944   ERROR: CPythonInvoker(27, C:\Users\htpc\AppData\Roaming\Kodi\addons\plugin.video.nakamori\nakamori.py): script didn't stop in 5 seconds - let's kill it
12:45:48.726 T:8944   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.nakamori/?mode=1&file_id=4213&ep_id=6997&serie_id=131&userrate=0.0&ui_index=1]
12:45:50.093 T:1456   ERROR: Nakamori 2.1.19 id: plugin.video.nakamori
12:45:50.093 T:1456   ERROR: ---Unicode Error---
12:45:50.093 T:1456   ERROR: On url: plugin://plugin.video.nakamori/?mode=1&file_id=4213&ep_id=6997&serie_id=131&userrate=0.0&ui_index=1
12:45:50.093 T:1456   ERROR: <type 'exceptions.SystemExit'> at line 483 in file util.py
12:45:50.093 T:1456   ERROR: Traceback (most recent call last):
12:45:50.093 T:1456   ERROR:   File "C:\Users\htpc\AppData\Roaming\Kodi\addons\plugin.video.nakamori\resources\lib\util.py", line 483, in encode
12:45:50.094 T:1456   ERROR:     try:
12:45:50.094 T:1456   ERROR: SystemExit
12:45:50.094 T:1456   ERROR: Nakamori 2.1.19 id: plugin.video.nakamori
12:45:50.094 T:1456   ERROR: ---url:http://10.10.10.19:8111/api/file/offset---
12:45:50.094 T:1456   ERROR: On url: plugin://plugin.video.nakamori/?mode=1&file_id=4213&ep_id=6997&serie_id=131&userrate=0.0&ui_index=1
12:45:50.094 T:1456   ERROR: <type 'exceptions.ValueError'> at line 427 in file util.py
12:45:50.094 T:1456   ERROR: Traceback (most recent call last):
12:45:50.094 T:1456   ERROR:   File "C:\Users\htpc\AppData\Roaming\Kodi\addons\plugin.video.nakamori\resources\lib\util.py", line 427, in post_data
12:45:50.094 T:1456   ERROR:     response = urllib2.urlopen(req, timeout=int(__addon__.getSetting('timeout')))
12:45:50.094 T:1456   ERROR:   File "C:\kodi\system\python\Lib\urllib2.py", line 154, in urlopen
12:45:50.096 T:1456   ERROR:     return opener.open(url, data, timeout)
12:45:50.096 T:1456   ERROR:   File "C:\kodi\system\python\Lib\urllib2.py", line 421, in open
12:45:50.096 T:1456   ERROR:     protocol = req.get_type()
12:45:50.096 T:1456   ERROR:   File "C:\kodi\system\python\Lib\urllib2.py", line 283, in get_type
12:45:50.096 T:1456   ERROR:     raise ValueError, "unknown url type: %s" % self.__original
12:45:50.096 T:1456   ERROR: ValueError: unknown url type:
12:45:50.096 T:1456   ERROR: Nakamori 2.1.19 id: plugin.video.nakamori
12:45:50.096 T:1456   ERROR: ---Connection Failed in post_data---
12:45:50.096 T:1456   ERROR: On url: plugin://plugin.video.nakamori/?mode=1&file_id=4213&ep_id=6997&serie_id=131&userrate=0.0&ui_index=1
12:45:50.096 T:1456   ERROR: <type 'exceptions.ValueError'> at line 427 in file util.py
12:45:50.096 T:1456   ERROR: Traceback (most recent call last):
12:45:50.096 T:1456   ERROR:   File "C:\Users\htpc\AppData\Roaming\Kodi\addons\plugin.video.nakamori\resources\lib\util.py", line 427, in post_data
12:45:50.096 T:1456   ERROR:     response = urllib2.urlopen(req, timeout=int(__addon__.getSetting('timeout')))
12:45:50.096 T:1456   ERROR:   File "C:\kodi\system\python\Lib\urllib2.py", line 154, in urlopen
12:45:50.096 T:1456   ERROR:     return opener.open(url, data, timeout)
12:45:50.096 T:1456   ERROR:   File "C:\kodi\system\python\Lib\urllib2.py", line 421, in open
12:45:50.096 T:1456   ERROR:     protocol = req.get_type()
12:45:50.096 T:1456   ERROR:   File "C:\kodi\system\python\Lib\urllib2.py", line 283, in get_type
12:45:50.096 T:1456   ERROR:     raise ValueError, "unknown url type: %s" % self.__original
```

**Comment by kaigame** [comment]
I thought i'd bring it up here, since the only situation i could get it to happen was via the nakamori plugin. I have now set the option to choose, and selecting play works everytime.

**Comment by da3dsoul** [comment]
Do you have the youtube app or something? That might be a way to check

**Comment by kaigame** [comment]
youtube app works fine, trailers app is fine, i don't have many other working apps.

**Comment by bigretromike** [comment]
It took time - probably was fixed long ago, but I tested this and this is not problem anymore in soon-to-release version 3.0.0
Thank you for the issue

**Comment by da3dsoul** [comment]
Ah ha

**Comment by da3dsoul** [comment]
Not hard to change back
