### ISSUE TITLE
Error on startup wizard

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#277]
nevermind I'm dumb, I was looking at the wrong log files. Freaking linux man.
This looks useful:
```
21:18:05.820 T:1711723264 WARNING: --- (get_shoko_status: wizard) ---
21:18:06.091 T:1541034752 WARNING: --- default.py : start
21:18:06.092 T:1541034752 WARNING: CSkinInfo: failed to load skin settings
21:18:06.093 T:1541034752   ERROR: GetDirectory - Error getting /root/.kodi/addons/script.module.nakamori/resources/skins/default
21:18:06.093 T:1541034752   ERROR: EXCEPTION: XML File for Window is missing
21:18:06.095 T:1541034752   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: XML File for Window is missing
                                            Traceback (most recent call last):
                                              File "/root/.kodi/addons/script.module.nakamori/default.py", line 30, in <module>
                                                Main()
                                              File "/root/.kodi/addons/script.module.nakamori/default.py", line 21, in __init__
                                                wizard.open_wizard()
                                              File "/root/.kodi/addons/script.module.nakamori/lib/windows/wizard.py", line 158, in open_wizard
                                                ui = Wizard2('wizard.xml', CWD, 'default', '1080i')
                                            RuntimeError: XML File for Window is missing
                                            -->End of Python script error report<--
21:19:11.998 T:1870656256  NOTICE: CAESinkPi:AddPackets Underrun (delay:0.00 frames:2205)
```

**Comment by bigretromike** [comment]
Looks like outdated `script.module.nakamori` remove nakamori and all packages and try again from repo.
