### ISSUE TITLE
Error Playing File Sometimes

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#309]
This is weird because it'll say there was an error, but it'll be playing behind the error message. The message is from Kodi and not Nakamori, as well.
Working Playback:
```
12:17:14.395 T:17664   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.nakamori/episode/108874/file/0/play]
12:17:14.404 T:19820  NOTICE: Nakamori|v2::File::__init__#L1428 -> {"is_kodi_folder": true, "server_path": "D:\\Media\\Video\\Other\\Hentai\\Yubisaki Annainin Shirudaku Settai Okawari Sanbai-me\\Yubisaki Annainin Shirudaku Settai Okawari Sanbai-me - 01 [EngSub][Audio fixed version][1080p].mkv", "group": "hampelmann000", "name": "Yubisaki Annainin Shirudaku Settai Okawari Sanbai-me - 01 [EngSub][Audio fixed version][1080p].mkv", "sizes": {}, "fanart": "", "items": [], "url_for_player": "http://15.129.1.5:8111/Stream/50718/2/False/file.mkv", "file_url": "http://15.129.1.5:8111/Stream/50718/2/False/file.mkv", "video_streams": {"width": 1920, "254": {"width": 1920, "codec": "h264", "aspect": 1.78, "height": 1080}, "height": 1080}, "get_children": false, "sort_index": 0, "audio_streams": {"0": {"channels": 2, "codec": "aac", "language": "jpn"}}, "resume_time": 0, "poster": "", "duration": 1227579, "date_added": "2019-03-02 00:06:22", "sub_streams": {"1": {"language": "eng"}}, "banner": "", "id": 50718, "size": 847967747}
12:17:14.408 T:19820  NOTICE: Nakamori|v2::Episode::__init__#L1112 -> {"rating": 7.48, "overview": "Episode Overview not Available", "year": 2010, "watched": false, "id": 108874, "alternate_name": "Volume 1", "size": 0, "is_kodi_folder": true, "votes": 1, "fanart": "http://15.129.1.5:8111/api/image/support/plex_404.png", "get_children": false, "user_rating": 0.0, "actors": [], "poster": "http://15.129.1.5:8111/api/image/support/plex_404.png", "tags": "", "season": 1, "series_name": {}, "series_id": 0, "series_anidb_id": 0, "date": "2010-09-17", "episode_number": 1, "banner": "", "tvdb_episode": "0x0", "outline": "Episode Overview not Available", "name": "Volume 1", "sizes": {}, "url": {}, "items": [{"is_kodi_folder": true, "server_path": "D:\\Media\\Video\\Other\\Hentai\\Yubisaki Annainin Shirudaku Settai Okawari Sanbai-me\\Yubisaki Annainin Shirudaku Settai Okawari Sanbai-me - 01 [EngSub][Audio fixed version][1080p].mkv", "group": "hampelmann000", "name": "Yubisaki Annainin Shirudaku Settai Okawari Sanbai-me - 01 [EngSub][Audio fixed version][1080p].mkv", "sizes": {}, "fanart": "", "items": [], "url_for_player": "http://15.129.1.5:8111/Stream/50718/2/False/file.mkv", "file_url": "http://15.129.1.5:8111/Stream/50718/2/False/file.mkv", "video_streams": {"width": 1920, "254": {"width": 1920, "codec": "h264", "aspect": 1.78, "height": 1080}, "height": 1080}, "get_children": false, "sort_index": 0, "audio_streams": {"0": {"channels": 2, "codec": "aac", "language": "jpn"}}, "resume_time": 0, "poster": "", "duration": 1227579, "date_added": "2019-03-02 00:06:22", "sub_streams": {"1": {"language": "eng"}}, "banner": "", "id": 50718, "size": 847967747}], "episode_type": "Episode", "sort_index": 0, "item_type": "episode"}
12:17:14.423 T:19820  NOTICE: Nakamori|v2::File::__init__#L1428 -> {"is_kodi_folder": true, "server_path": "D:\\Media\\Video\\Other\\Hentai\\Yubisaki Annainin Shirudaku Settai Okawari Sanbai-me\\Yubisaki Annainin Shirudaku Settai Okawari Sanbai-me - 01 [EngSub][Audio fixed version][1080p].mkv", "group": "hampelmann000", "name": "Yubisaki Annainin Shirudaku Settai Okawari Sanbai-me - 01 [EngSub][Audio fixed version][1080p].mkv", "sizes": {}, "fanart": "", "items": [], "url_for_player": "http://15.129.1.5:8111/Stream/50718/2/False/file.mkv", "file_url": "http://15.129.1.5:8111/Stream/50718/2/False/file.mkv", "video_streams": {"width": 1920, "254": {"width": 1920, "codec": "h264", "aspect": 1.78, "height": 1080}, "height": 1080}, "get_children": false, "sort_index": 0, "audio_streams": {"0": {"channels": 2, "codec": "aac", "language": "jpn"}}, "resume_time": 0, "poster": "", "duration": 1227579, "date_added": "2019-03-02 00:06:22", "sub_streams": {"1": {"language": "eng"}}, "banner": "", "id": 50718, "size": 847967747}
12:17:14.426 T:19820  NOTICE: Nakamori|v2::Episode::__init__#L1112 -> {"rating": 7.48, "overview": "Episode Overview not Available", "year": 2010, "watched": false, "id": 108874, "alternate_name": "Volume 1", "size": 0, "is_kodi_folder": true, "votes": 1, "fanart": "http://15.129.1.5:8111/api/image/support/plex_404.png", "get_children": false, "user_rating": 0.0, "actors": [], "poster": "http://15.129.1.5:8111/api/image/support/plex_404.png", "tags": "", "season": 1, "series_name": {}, "series_id": 0, "series_anidb_id": 0, "date": "2010-09-17", "episode_number": 1, "banner": "", "tvdb_episode": "0x0", "outline": "Episode Overview not Available", "name": "Volume 1", "sizes": {}, "url": {}, "items": [{"is_kodi_folder": true, "server_path": "D:\\Media\\Video\\Other\\Hentai\\Yubisaki Annainin Shirudaku Settai Okawari Sanbai-me\\Yubisaki Annainin Shirudaku Settai Okawari Sanbai-me - 01 [EngSub][Audio fixed version][1080p].mkv", "group": "hampelmann000", "name": "Yubisaki Annainin Shirudaku Settai Okawari Sanbai-me - 01 [EngSub][Audio fixed version][1080p].mkv", "sizes": {}, "fanart": "", "items": [], "url_for_player": "http://15.129.1.5:8111/Stream/50718/2/False/file.mkv", "file_url": "http://15.129.1.5:8111/Stream/50718/2/False/file.mkv", "video_streams": {"width": 1920, "254": {"width": 1920, "codec": "h264", "aspect": 1.78, "height": 1080}, "height": 1080}, "get_children": false, "sort_index": 0, "audio_streams": {"0": {"channels": 2, "codec": "aac", "language": "jpn"}}, "resume_time": 0, "poster": "", "duration": 1227579, "date_added": "2019-03-02 00:06:22", "sub_streams": {"1": {"language": "eng"}}, "banner": "", "id": 50718, "size": 847967747}], "episode_type": "Episode", "sort_index": 0, "item_type": "episode"}
12:17:14.438 T:19820  NOTICE: Nakamori|v2::Series::__init__#L677 -> {"rating": 3.3, "overview": "", "year": "2010", "file_size": 0, "anidb_id": 7677, "id": 2636, "alternate_name": "Yubisaki Annainin Shirudaku Settai Okawari Sanbai-me", "size": 3, "is_kodi_folder": true, "votes": 152, "fanart": "", "mpaa": "", "is_movie": false, "get_children": false, "user_rating": 0.0, "actors": [], "season": 1, "tags": "office lady | fetishes | 18 restricted | rape | anal | gang bang | BDSM | large breasts | sex | nudity | game | erotic game | visual novel | pornography | deflowering | bondage | sexual abuse", "poster": "http://15.129.1.5:8111/api/image/1/7677", "episode_types": [], "date": "2010-09-16", "banner": "", "outline": "", "name": "Yubisaki Annainin Shirudaku Settai Okawari Sanbai-me", "sizes": {"local_episodes": 3, "watched_total": 0, "total_specials": 0, "total_episodes": 3, "local_total": 3, "local_specials": 0, "watched_episodes": 0, "total": 3, "watched_specials": 0}, "url": {}, "items": [], "sort_index": 0, "item_type": "tvshow"}
12:17:14.465 T:19820  NOTICE: Nakamori|nakamori_player::Player::__init__#L253 -> Player Initialized
12:17:14.481 T:19820  NOTICE: Nakamori|nakamori_player::Player::__init__#L275 -> {"Playlist": {}, "Shuffle": false, "time": 0, "CanControl": true, "ep_id": 0, "LoopStatus": "None", "_t": {}, "_s": {}, "is_movie": {}, "PlaybackStatus": "Stopped", "is_transcoded": false, "file_id": 0, "_details": {}, "duration": 0, "path": "", "scrobble": true}
12:17:14.483 T:19820  NOTICE: Nakamori|nakamori_player::Player::feed#L285 -> Player feed - file_id=50718 ep_id=108874 duration=1227579 path=http://15.129.1.5:8111/Stream/50718/2/False/file.mkv scrobble=True
12:17:14.542 T:17664  NOTICE: VideoPlayer: Opening: http://15.129.1.5:8111/Stream/50718/2/False/file.mkv
12:17:14.542 T:17664 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
12:17:14.576 T:17664   ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 105 for 1.
12:17:14.577 T:9872  NOTICE: Creating InputStream
12:17:14.665 T:9872  NOTICE: Creating Demuxer
12:17:14.814 T:9872  NOTICE: Opening stream: 0 source: 256
12:17:14.814 T:9872  NOTICE: Creating video codec with codec id: 28
12:17:14.814 T:9872  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
12:17:14.815 T:9872  NOTICE: Creating video thread
12:17:14.815 T:9872  NOTICE: Opening stream: 1 source: 256
12:17:14.815 T:9872  NOTICE: Finding audio codec for: 86018
12:17:14.815 T:1876  NOTICE: running thread: video_thread
12:17:14.816 T:9872  NOTICE: Creating audio thread
12:17:14.816 T:9872  NOTICE: Opening stream: 2 source: 256
12:17:14.816 T:16936  NOTICE: running thread: CVideoPlayerAudio::Process()
12:17:15.955 T:1876  NOTICE: CDVDVideoCodecFFmpeg::GetFormat - Creating DXVA(1920x1080)
12:17:15.963 T:16936  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 48000, no pass-through)
12:17:15.996 T:19820  NOTICE: Nakamori|nakamori_player::Player::onPlayBackStarted#L293 -> Playback Started
12:17:16.015 T:17664  NOTICE: D3D: rendering method forced to DXVA processor
12:17:16.015 T:17664  NOTICE: DXVA::CProcessorHD::InitProcessor: Supported deinterlace methods: Blend:no, Bob:yes, Adaptive:yes, MoComp:yes.
12:17:16.016 T:17664 WARNING: CWinRenderer::UpdateVideoFilter - chosen scaling method 1 is not supported by renderer
12:17:16.031 T:17664  NOTICE: Display resolution ADJUST : 1920x1080@ 60.00 - Full Screen (16) (weight: 0.001)
12:17:16.329 T:1876  NOTICE: CDVDVideoCodecFFmpeg::CDropControl: calculated diff time: 41636
12:17:16.877 T:17664  NOTICE: CVideoPlayer::CloseFile()
12:17:16.877 T:17664  NOTICE: VideoPlayer: waiting for threads to exit
12:17:16.883 T:9872  NOTICE: CVideoPlayer::OnExit()
12:17:16.883 T:9872  NOTICE: Closing stream player 1
12:17:16.883 T:9872  NOTICE: Waiting for audio thread to exit
12:17:16.887 T:16936  NOTICE: thread end: CVideoPlayerAudio::OnExit()
12:17:16.887 T:9872  NOTICE: Closing audio device
12:17:16.903 T:9872  NOTICE: Deleting audio codec
12:17:16.903 T:9872  NOTICE: Closing stream player 2
12:17:16.903 T:9872  NOTICE: waiting for video thread to exit
12:17:16.912 T:1876  NOTICE: thread end: video_thread
12:17:16.913 T:9872  NOTICE: deleting video codec
12:17:16.916 T:9872  NOTICE: DXVA::CDecoder::Close - closing decoder
12:17:16.916 T:9872  NOTICE: DXVA::Close - closing decoder context
12:17:16.916 T:9872  NOTICE: Closing stream player 3
12:17:16.933 T:17664  NOTICE: VideoPlayer: finished waiting
12:17:16.986 T:17664   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
12:17:16.988 T:17664  NOTICE: CVideoPlayer::CloseFile()
12:17:16.988 T:17664  NOTICE: VideoPlayer: waiting for threads to exit
12:17:16.988 T:17664  NOTICE: VideoPlayer: finished waiting
12:17:16.988 T:17664  NOTICE: CVideoPlayer::CloseFile()
12:17:16.988 T:17664  NOTICE: VideoPlayer: waiting for threads to exit
12:17:16.988 T:17664  NOTICE: VideoPlayer: finished waiting
12:17:19.567 T:10644  NOTICE: Nakamori|nakamori_player::Player::tick_loop_shoko#L392 -> sync_thread: not playing anything
12:17:19.736 T:19820  NOTICE: Nakamori|nakamori_player::Player::onPlayBackStopped#L335 -> Playback Stopped
12:17:19.761 T:19820  NOTICE: Nakamori|nakamori_player::finished_episode#L45 -> mark = 0.8 * total = 1227 = 981.6 < current = 0.0440000034869
12:17:19.815 T:19820  NOTICE: Nakamori|nakamori_player::finished_episode#L64 -> mark = watched but it was unsort file
12:17:20.130 T:19820  NOTICE: Nakamori|nakamori_player::player_loop#L142 -> Playback Ended - Shutting Down: 0
```
Not Working Playback:
```
12:17:24.539 T:17664   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.nakamori/episode/108874/file/0/play]
12:17:24.544 T:6740  NOTICE: Nakamori|v2::File::__init__#L1428 -> {"is_kodi_folder": true, "server_path": "D:\\Media\\Video\\Other\\Hentai\\Yubisaki Annainin Shirudaku Settai Okawari Sanbai-me\\Yubisaki Annainin Shirudaku Settai Okawari Sanbai-me - 01 [EngSub][Audio fixed version][1080p].mkv", "group": "hampelmann000", "name": "Yubisaki Annainin Shirudaku Settai Okawari Sanbai-me - 01 [EngSub][Audio fixed version][1080p].mkv", "sizes": {}, "fanart": "", "items": [], "url_for_player": "http://15.129.1.5:8111/Stream/50718/2/False/file.mkv", "file_url": "http://15.129.1.5:8111/Stream/50718/2/False/file.mkv", "video_streams": {"width": 1920, "254": {"width": 1920, "codec": "h264", "aspect": 1.78, "height": 1080}, "height": 1080}, "get_children": false, "sort_index": 0, "audio_streams": {"0": {"channels": 2, "codec": "aac", "language": "jpn"}}, "resume_time": 0, "poster": "", "duration": 1227579, "date_added": "2019-03-02 00:06:22", "sub_streams": {"1": {"language": "eng"}}, "banner": "", "id": 50718, "size": 847967747}
12:17:24.547 T:6740  NOTICE: Nakamori|v2::Episode::__init__#L1112 -> {"rating": 7.48, "overview": "Episode Overview not Available", "year": 2010, "watched": false, "id": 108874, "alternate_name": "Volume 1", "size": 0, "is_kodi_folder": true, "votes": 1, "fanart": "http://15.129.1.5:8111/api/image/support/plex_404.png", "get_children": false, "user_rating": 0.0, "actors": [], "poster": "http://15.129.1.5:8111/api/image/support/plex_404.png", "tags": "", "season": 1, "series_name": {}, "series_id": 0, "series_anidb_id": 0, "date": "2010-09-17", "episode_number": 1, "banner": "", "tvdb_episode": "0x0", "outline": "Episode Overview not Available", "name": "Volume 1", "sizes": {}, "url": {}, "items": [{"is_kodi_folder": true, "server_path": "D:\\Media\\Video\\Other\\Hentai\\Yubisaki Annainin Shirudaku Settai Okawari Sanbai-me\\Yubisaki Annainin Shirudaku Settai Okawari Sanbai-me - 01 [EngSub][Audio fixed version][1080p].mkv", "group": "hampelmann000", "name": "Yubisaki Annainin Shirudaku Settai Okawari Sanbai-me - 01 [EngSub][Audio fixed version][1080p].mkv", "sizes": {}, "fanart": "", "items": [], "url_for_player": "http://15.129.1.5:8111/Stream/50718/2/False/file.mkv", "file_url": "http://15.129.1.5:8111/Stream/50718/2/False/file.mkv", "video_streams": {"width": 1920, "254": {"width": 1920, "codec": "h264", "aspect": 1.78, "height": 1080}, "height": 1080}, "get_children": false, "sort_index": 0, "audio_streams": {"0": {"channels": 2, "codec": "aac", "language": "jpn"}}, "resume_time": 0, "poster": "", "duration": 1227579, "date_added": "2019-03-02 00:06:22", "sub_streams": {"1": {"language": "eng"}}, "banner": "", "id": 50718, "size": 847967747}], "episode_type": "Episode", "sort_index": 0, "item_type": "episode"}
12:17:24.556 T:6740  NOTICE: Nakamori|v2::File::__init__#L1428 -> {"is_kodi_folder": true, "server_path": "D:\\Media\\Video\\Other\\Hentai\\Yubisaki Annainin Shirudaku Settai Okawari Sanbai-me\\Yubisaki Annainin Shirudaku Settai Okawari Sanbai-me - 01 [EngSub][Audio fixed version][1080p].mkv", "group": "hampelmann000", "name": "Yubisaki Annainin Shirudaku Settai Okawari Sanbai-me - 01 [EngSub][Audio fixed version][1080p].mkv", "sizes": {}, "fanart": "", "items": [], "url_for_player": "http://15.129.1.5:8111/Stream/50718/2/False/file.mkv", "file_url": "http://15.129.1.5:8111/Stream/50718/2/False/file.mkv", "video_streams": {"width": 1920, "254": {"width": 1920, "codec": "h264", "aspect": 1.78, "height": 1080}, "height": 1080}, "get_children": false, "sort_index": 0, "audio_streams": {"0": {"channels": 2, "codec": "aac", "language": "jpn"}}, "resume_time": 0, "poster": "", "duration": 1227579, "date_added": "2019-03-02 00:06:22", "sub_streams": {"1": {"language": "eng"}}, "banner": "", "id": 50718, "size": 847967747}
12:17:24.558 T:6740  NOTICE: Nakamori|v2::Episode::__init__#L1112 -> {"rating": 7.48, "overview": "Episode Overview not Available", "year": 2010, "watched": false, "id": 108874, "alternate_name": "Volume 1", "size": 0, "is_kodi_folder": true, "votes": 1, "fanart": "http://15.129.1.5:8111/api/image/support/plex_404.png", "get_children": false, "user_rating": 0.0, "actors": [], "poster": "http://15.129.1.5:8111/api/image/support/plex_404.png", "tags": "", "season": 1, "series_name": {}, "series_id": 0, "series_anidb_id": 0, "date": "2010-09-17", "episode_number": 1, "banner": "", "tvdb_episode": "0x0", "outline": "Episode Overview not Available", "name": "Volume 1", "sizes": {}, "url": {}, "items": [{"is_kodi_folder": true, "server_path": "D:\\Media\\Video\\Other\\Hentai\\Yubisaki Annainin Shirudaku Settai Okawari Sanbai-me\\Yubisaki Annainin Shirudaku Settai Okawari Sanbai-me - 01 [EngSub][Audio fixed version][1080p].mkv", "group": "hampelmann000", "name": "Yubisaki Annainin Shirudaku Settai Okawari Sanbai-me - 01 [EngSub][Audio fixed version][1080p].mkv", "sizes": {}, "fanart": "", "items": [], "url_for_player": "http://15.129.1.5:8111/Stream/50718/2/False/file.mkv", "file_url": "http://15.129.1.5:8111/Stream/50718/2/False/file.mkv", "video_streams": {"width": 1920, "254": {"width": 1920, "codec": "h264", "aspect": 1.78, "height": 1080}, "height": 1080}, "get_children": false, "sort_index": 0, "audio_streams": {"0": {"channels": 2, "codec": "aac", "language": "jpn"}}, "resume_time": 0, "poster": "", "duration": 1227579, "date_added": "2019-03-02 00:06:22", "sub_streams": {"1": {"language": "eng"}}, "banner": "", "id": 50718, "size": 847967747}], "episode_type": "Episode", "sort_index": 0, "item_type": "episode"}
12:17:24.566 T:6740  NOTICE: Nakamori|v2::Series::__init__#L677 -> {"rating": 3.3, "overview": "", "year": "2010", "file_size": 0, "anidb_id": 7677, "id": 2636, "alternate_name": "Yubisaki Annainin Shirudaku Settai Okawari Sanbai-me", "size": 3, "is_kodi_folder": true, "votes": 152, "fanart": "", "mpaa": "", "is_movie": false, "get_children": false, "user_rating": 0.0, "actors": [], "season": 1, "tags": "office lady | fetishes | 18 restricted | rape | anal | gang bang | BDSM | large breasts | sex | nudity | game | erotic game | visual novel | pornography | deflowering | bondage | sexual abuse", "poster": "http://15.129.1.5:8111/api/image/1/7677", "episode_types": [], "date": "2010-09-16", "banner": "", "outline": "", "name": "Yubisaki Annainin Shirudaku Settai Okawari Sanbai-me", "sizes": {"local_episodes": 3, "watched_total": 0, "total_specials": 0, "total_episodes": 3, "local_total": 3, "local_specials": 0, "watched_episodes": 0, "total": 3, "watched_specials": 0}, "url": {}, "items": [], "sort_index": 0, "item_type": "tvshow"}
12:17:24.575 T:6740  NOTICE: Nakamori|nakamori_player::Player::__init__#L253 -> Player Initialized
12:17:24.589 T:6740  NOTICE: Nakamori|nakamori_player::Player::__init__#L275 -> {"Playlist": {}, "Shuffle": false, "time": 0, "CanControl": true, "ep_id": 0, "LoopStatus": "None", "_t": {}, "_s": {}, "is_movie": {}, "PlaybackStatus": "Stopped", "is_transcoded": false, "file_id": 0, "_details": {}, "duration": 0, "path": "", "scrobble": true}
12:17:24.590 T:6740  NOTICE: Nakamori|nakamori_player::Player::feed#L285 -> Player feed - file_id=50718 ep_id=108874 duration=1227579 path=http://15.129.1.5:8111/Stream/50718/2/False/file.mkv scrobble=True
12:17:24.659 T:17664  NOTICE: VideoPlayer: Opening: http://15.129.1.5:8111/Stream/50718/2/False/file.mkv
12:17:24.659 T:17664 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
12:17:24.834 T:17664   ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 105 for 1.
12:17:24.836 T:5836  NOTICE: Creating InputStream
12:17:24.923 T:5836  NOTICE: Creating Demuxer
12:17:25.077 T:5836  NOTICE: Opening stream: 0 source: 256
12:17:25.077 T:5836  NOTICE: Creating video codec with codec id: 28
12:17:25.077 T:5836  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
12:17:25.077 T:5836  NOTICE: Creating video thread
12:17:25.077 T:5836  NOTICE: Opening stream: 1 source: 256
12:17:25.078 T:5836  NOTICE: Finding audio codec for: 86018
12:17:25.078 T:16428  NOTICE: running thread: video_thread
12:17:25.078 T:5836  NOTICE: Creating audio thread
12:17:25.079 T:5836  NOTICE: Opening stream: 2 source: 256
12:17:25.079 T:20788  NOTICE: running thread: CVideoPlayerAudio::Process()
12:17:26.290 T:16428  NOTICE: CDVDVideoCodecFFmpeg::GetFormat - Creating DXVA(1920x1080)
12:17:26.295 T:20788  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 48000, no pass-through)
12:17:26.353 T:17664  NOTICE: D3D: rendering method forced to DXVA processor
12:17:26.353 T:17664  NOTICE: DXVA::CProcessorHD::InitProcessor: Supported deinterlace methods: Blend:no, Bob:yes, Adaptive:yes, MoComp:yes.
12:17:26.354 T:17664 WARNING: CWinRenderer::UpdateVideoFilter - chosen scaling method 1 is not supported by renderer
12:17:26.358 T:17664  NOTICE: Display resolution ADJUST : 1920x1080@ 60.00 - Full Screen (16) (weight: 0.001)
12:17:26.408 T:6740  NOTICE: Nakamori|nakamori_player::Player::onPlayBackStarted#L293 -> Playback Started
12:17:26.688 T:16428  NOTICE: CDVDVideoCodecFFmpeg::CDropControl: calculated diff time: 41636
12:17:26.834 T:17664  NOTICE: CVideoPlayer::CloseFile()
12:17:26.834 T:17664  NOTICE: VideoPlayer: waiting for threads to exit
12:17:26.835 T:5836  NOTICE: CVideoPlayer::OnExit()
12:17:26.835 T:5836  NOTICE: Closing stream player 1
12:17:26.835 T:5836  NOTICE: Waiting for audio thread to exit
12:17:26.841 T:20788  NOTICE: thread end: CVideoPlayerAudio::OnExit()
12:17:26.841 T:5836  NOTICE: Closing audio device
12:17:26.856 T:5836  NOTICE: Deleting audio codec
12:17:26.856 T:5836  NOTICE: Closing stream player 2
12:17:26.856 T:5836  NOTICE: waiting for video thread to exit
12:17:26.871 T:16428  NOTICE: thread end: video_thread
12:17:26.872 T:5836  NOTICE: deleting video codec
12:17:26.875 T:5836  NOTICE: DXVA::CDecoder::Close - closing decoder
12:17:26.875 T:5836  NOTICE: DXVA::Close - closing decoder context
12:17:26.875 T:5836  NOTICE: Closing stream player 3
12:17:26.889 T:17664  NOTICE: VideoPlayer: finished waiting
12:17:26.925 T:17664  NOTICE: CVideoPlayer::CloseFile()
12:17:26.926 T:17664  NOTICE: VideoPlayer: waiting for threads to exit
12:17:26.926 T:17664  NOTICE: VideoPlayer: finished waiting
12:17:26.947 T:17664   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
12:17:28.752 T:17664  NOTICE: Storing total System Uptime
12:17:28.752 T:17664  NOTICE: Saving settings
12:17:28.775 T:17664  NOTICE: Saving skin settings
12:17:28.790 T:17664  NOTICE: stop all
12:17:29.677 T:11596  NOTICE: Nakamori|nakamori_player::Player::tick_loop_shoko#L392 -> sync_thread: not playing anything
12:17:29.833 T:6740  NOTICE: Nakamori|nakamori_player::Player::onPlayBackStopped#L335 -> Playback Stopped
12:17:29.859 T:6740  NOTICE: Nakamori|nakamori_player::finished_episode#L45 -> mark = 0.8 * total = 1227 = 981.6 < current = -0.0900000035763
12:17:29.932 T:6740  NOTICE: Nakamori|nakamori_player::finished_episode#L64 -> mark = watched but it was unsort file
12:17:30.178 T:6740  NOTICE: Nakamori|nakamori_player::player_loop#L142 -> Playback Ended - Shutting Down: 0
```

**Comment by da3dsoul** [comment]
Found the issue somewhere. Don't set IsPlayable on ListItems when using Player().play()

**Comment by bigretromike** [comment]
why ?:-)
I found other bug:

```
2019-04-10 19:26:56.593 T:3024   ERROR: Nakamori|Logger -> There was an error while executing Nakamori.
2019-04-10 19:26:56.593 T:3024   ERROR: Nakamori|Logger -> Nakamori Version 3.1.0~beta20
2019-04-10 19:26:56.593 T:3024   ERROR: Nakamori|Logger -> The url accessed was plugin://plugin.video.nakamori/menu/series/38/type/Episode
2019-04-10 19:26:56.593 T:3024   ERROR: Nakamori|Logger -> Unable to Select Item -- Exception: AttributeError at ./script.module.nakamori-lib/lib/nakamori_utils/kodi_utils.py::move_position_on_list#L261
2019-04-10 19:26:56.594 T:3024   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\brm\AppData\Roaming\Kodi\addons\plugin.video.nakamori\nakamoriplugin.py", line 530, in <module>
                                                show_messages()
                                              File "C:\Users\brm\AppData\Roaming\Kodi\addons\script.module.nakamori-lib\lib\error_handler.py", line 283, in show_messages
                                                show_notification_for_exception(exes[0])
                                              File "C:\Users\brm\AppData\Roaming\Kodi\addons\script.module.nakamori-lib\lib\error_handler.py", line 364, in show_notification_for_exception
                                                msg = ex[0].exc_message + '\nThis occurred ' + str(ex[1]) + pp.encode(u'\u00D7 ') + ' times.'
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
                                            -->End of Python script error report<--
```

**Comment by da3dsoul** [comment]
I know. I already fix that

**Comment by bigretromike** [comment]
Looks like you fix'd it, close ?

**Comment by da3dsoul** [comment]
Yeah
