### ISSUE TITLE
Can't login with wizard

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#310]
```
2019-04-11 11:21:06.286 T:11936   ERROR: Nakamori|Logger -> There was an error while executing Nakamori.
2019-04-11 11:21:06.286 T:11936   ERROR: Nakamori|Logger -> Nakamori Version 3.1.0~beta20
2019-04-11 11:21:06.286 T:11936   ERROR: Nakamori|Logger -> The url accessed was plugin://plugin.video.nakamori/
2019-04-11 11:21:06.286 T:11936   ERROR: Nakamori|Logger -> Could not log in. Please check your user settings. -- Exception: RuntimeError at ./plugin.video.nakamori/nakamoriplugin.py#L529
2019-04-11 11:21:06.286 T:11936   ERROR: Nakamori|Logger -> Traceback (most recent call last):
2019-04-11 11:21:06.286 T:11936   ERROR: Nakamori|Logger ->   File "./plugin.video.nakamori/nakamoriplugin.py", line 523, in main
2019-04-11 11:21:06.286 T:11936   ERROR: Nakamori|Logger ->     raise RuntimeError(plugin_localize(30158))
2019-04-11 11:21:06.286 T:11936   ERROR: Nakamori|Logger -> RuntimeError: Could not log in. Please check your user settings.
2019-04-11 11:21:10.118 T:11908   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.nakamori/
2019-04-11 11:21:10.123 T:11516   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.nakamori/) failed
2019-04-11 11:21:11.776 T:3252   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: Required argument 'heading' (pos 2) not found
                                            Traceback (most recent call last):
                                              File "C:\Users\brm\AppData\Roaming\Kodi\addons\script.module.nakamori\lib\windows\wizard.py", line 86, in onInit
                                                self._box_password.setType(xbmcgui.INPUT_PASSWORD)
                                            TypeError: Required argument 'heading' (pos 2) not found
                                            -->End of Python script error report<--
```

**Comment by bigretromike** [comment]
This error was about missing argument, but fixing that didn't resolve being unable to log thru new-rewriten wizard.

**Comment by bigretromike** [comment]
Clicking 'OK' don't send anything outside;

**Comment by bigretromike** [comment]
My fault;
