### ISSUE TITLE
Random crashes in script.module.routing

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#328]
For no reason from time to time I get this error - its some time now that this is happening.
Only solution I found is to restart Kodi and the issue resolve itself for longer time.
Any ideas ?

```
2019-05-22 18:31:38.584 T:8564   ERROR: Nakamori|Logger -> There was an error while executing Nakamori.
2019-05-22 18:31:38.584 T:8564   ERROR: Nakamori|Logger -> Nakamori Version 3.2.0
2019-05-22 18:31:38.584 T:8564   ERROR: Nakamori|Logger -> The url accessed was
2019-05-22 18:31:38.584 T:8564   ERROR: Nakamori|Logger -> No route to path "" -- Exception: RoutingError at ./script.module.nakamori/nakamoriscript.py#L294
2019-05-22 18:31:38.584 T:8564   ERROR: Nakamori|Logger -> Traceback (most recent call last):
2019-05-22 18:31:38.584 T:8564   ERROR: Nakamori|Logger ->   File "./script.module.routing/lib/routing.py", line 196, in run
2019-05-22 18:31:38.584 T:8564   ERROR: Nakamori|Logger ->     self._dispatch(path)
2019-05-22 18:31:38.584 T:8564   ERROR: Nakamori|Logger ->   File "./script.module.routing/lib/routing.py", line 148, in _dispatch
2019-05-22 18:31:38.584 T:8564   ERROR: Nakamori|Logger ->     raise RoutingError('No route to path "%s"' % path)
2019-05-22 18:31:38.584 T:8564   ERROR: Nakamori|Logger -> RoutingError: No route to path ""
```

**Comment by bigretromike** [comment]
I don't remember the last time this did happened. 
Closing, if this will be triggered again I will open new issue with logs from latest kodi/nakamori/routing version.
