### ISSUE TITLE
Clean install requires kodi restart to make wizard working

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#329]
Reported Baine @ Discord:

```
2019-05-22 19:32:23.082 T:16448   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed
2019-05-22 19:32:25.734 T:11512   ERROR: Nakamori|Logger -> There was an error while executing Nakamori.
2019-05-22 19:32:25.734 T:11512   ERROR: Nakamori|Logger -> Nakamori Version 3.2.0
2019-05-22 19:32:25.734 T:11512   ERROR: Nakamori|Logger -> The url accessed was plugin://plugin.video.nakamori/
2019-05-22 19:32:25.734 T:11512   ERROR: Nakamori|Logger -> expected string or buffer -- Exception: TypeError at ./plugin.video.nakamori/nakamoriplugin.py#L566
2019-05-22 19:32:25.734 T:11512   ERROR: Nakamori|Logger -> Traceback (most recent call last):
2019-05-22 19:32:25.734 T:11512   ERROR: Nakamori|Logger ->   File "./plugin.video.nakamori/nakamoriplugin.py", line 551, in main
2019-05-22 19:32:25.734 T:11512   ERROR: Nakamori|Logger ->     auth = shoko_utils.auth()
2019-05-22 19:32:25.734 T:11512   ERROR: Nakamori|Logger ->   File "./script.module.nakamori-lib/lib/nakamori_utils/shoko_utils.py", line 334, in auth
2019-05-22 19:32:25.734 T:11512   ERROR: Nakamori|Logger ->     apikey = get_apikey(login, password)
2019-05-22 19:32:25.734 T:11512   ERROR: Nakamori|Logger ->   File "./script.module.nakamori-lib/lib/nakamori_utils/shoko_utils.py", line 348, in get_apikey
2019-05-22 19:32:25.734 T:11512   ERROR: Nakamori|Logger ->     auth_body = json.loads(post_body)
2019-05-22 19:32:25.734 T:11512   ERROR: Nakamori|Logger ->   File "C:/Program Files/Kodi/system/python/Lib/json/__init__.py", line 339, in loads
2019-05-22 19:32:25.734 T:11512   ERROR: Nakamori|Logger ->     return _default_decoder.decode(s)
2019-05-22 19:32:25.734 T:11512   ERROR: Nakamori|Logger ->   File "C:/Program Files/Kodi/system/python/Lib/json/decoder.py", line 364, in decode
2019-05-22 19:32:25.734 T:11512   ERROR: Nakamori|Logger ->     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2019-05-22 19:32:25.734 T:11512   ERROR: Nakamori|Logger -> TypeError: expected string or buffer
```

**Comment by bigretromike** [comment]
@da3dsoul you played with this, any ideas?

The only thing that came up to my mind is that when you start it first time maybe the settings ain't saved and then it try to on-fly-settings ?

**Comment by bigretromike** [comment]
not allways

**Comment by bigretromike** [comment]
the only issue with clean installation for now is service dependency.
Closing this, as service issue clock this problem or this problem is non-existing anymore.
