### ISSUE TITLE
Error to fix later

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#343]
- [x] search 'hack roots' on bb
```
2019-08-07 17:13:44.369 T:139629496018688   ERROR: GetDirectory - Error getting plugin://plugin.video.nakamori/dialog/search/True
2019-08-07 17:13:44.369 T:139629982377728   ERROR: Nakamori|Logger -> There was an error while executing Nakamori.
2019-08-07 17:13:44.369 T:139629982377728   ERROR: Nakamori|Logger -> Nakamori Version 3.3.0
2019-08-07 17:13:44.369 T:139629982377728   ERROR: Nakamori|Logger -> The url accessed was plugin://plugin.video.nakamori/dialog/search/True
2019-08-07 17:13:44.369 T:139629982377728   ERROR: Nakamori|Logger -> 'size' -- Exception: KeyError at ./plugin.video.nakamori/nakamoriplugin.py::Plugin::main#L620
2019-08-07 17:13:44.369 T:139629982377728   ERROR: Nakamori|Logger -> Traceback (most recent call last):
2019-08-07 17:13:44.369 T:139629982377728   ERROR: Nakamori|Logger ->   File "./plugin.video.nakamori/nakamoriplugin.py", line 388, in new_search
2019-08-07 17:13:44.369 T:139629982377728   ERROR: Nakamori|Logger ->     show_search_result_menu(pyproxy.quote(pyproxy.quote(query)))
2019-08-07 17:13:44.369 T:139629982377728   ERROR: Nakamori|Logger ->   File "./plugin.video.nakamori/nakamoriplugin.py", line 401, in show_search_result_menu
2019-08-07 17:13:44.369 T:139629982377728   ERROR: Nakamori|Logger ->     if groups['size'] == 0:
2019-08-07 17:13:44.369 T:139629982377728   ERROR: Nakamori|Logger -> KeyError: 'size'
2019-08-07 17:13:44.370 T:139631163763392   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.nakamori/dialog/search/True) failed
```

**Comment by bigretromike** [comment]
- [ ] invalid literal for int() with base 10: ''
```
2019-08-08 13:58:02.213 T:18446744073709551614   ERROR: Nakamori|Logger -> There was an error while executing Nakamori.
2019-08-08 13:58:02.213 T:18446744073709551614   ERROR: Nakamori|Logger -> Nakamori Version 3.4.0~beta1
2019-08-08 13:58:02.213 T:18446744073709551614   ERROR: Nakamori|Logger -> The url accessed was nakamoriscript.py
2019-08-08 13:58:02.213 T:18446744073709551614   ERROR: Nakamori|Logger -> invalid literal for int() with base 10: '' -- Exception: ValueError at ./script.module.nakamori/nakamoriscript.py#L371
2019-08-08 13:58:02.213 T:18446744073709551614   ERROR: Nakamori|Logger -> Traceback (most recent call last):
2019-08-08 13:58:02.213 T:18446744073709551614   ERROR: Nakamori|Logger ->   File "./script.module.routing/lib/routing.py", line 190, in run
2019-08-08 13:58:02.213 T:18446744073709551614   ERROR: Nakamori|Logger ->     self._dispatch(path)
2019-08-08 13:58:02.213 T:18446744073709551614   ERROR: Nakamori|Logger ->   File "./script.module.routing/lib/routing.py", line 152, in _dispatch
2019-08-08 13:58:02.213 T:18446744073709551614   ERROR: Nakamori|Logger ->     view_func(**kwargs)
2019-08-08 13:58:02.213 T:18446744073709551614   ERROR: Nakamori|Logger ->   File "./script.module.nakamori/nakamoriscript.py", line 163, in remove_search_term
2019-08-08 13:58:02.213 T:18446744073709551614   ERROR: Nakamori|Logger ->     refresh()
2019-08-08 13:58:02.213 T:18446744073709551614   ERROR: Nakamori|Logger ->   File "./script.module.nakamori/nakamoriscript.py", line 184, in refresh
2019-08-08 13:58:02.213 T:18446744073709551614   ERROR: Nakamori|Logger ->     kodi_utils.refresh()
2019-08-08 13:58:02.213 T:18446744073709551614   ERROR: Nakamori|Logger ->   File "./script.module.nakamori-lib/lib/nakamori_utils/kodi_utils.py", line 273, in refresh
2019-08-08 13:58:02.213 T:18446744073709551614   ERROR: Nakamori|Logger ->     xbmc.sleep(int(plugin_addon.getSetting('refresh_wait')))
2019-08-08 13:58:02.213 T:18446744073709551614   ERROR: Nakamori|Logger -> ValueError: invalid literal for int() with base 10: ''
```
