### ISSUE TITLE
Small things that need a tweak (part2)

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#355]
- [x] adding bookmark/favorite could used a notification (maybe without option)
- [x] quick search, not working
- [x] try to fix search (back) issue asking for keyboard
- [x] after watching video `select` is move twice (very rare)
- [x] ac_calendar (see log)
- ~~[ ] try to add party_mode (add all episodes with the one clicked to playlist - check if vote need to be disabled)~~ moved out: https://github.com/bigretromike/nakamori/issues/356
- [x] ~~installation on android check log~~
- [x] no way to scroll 3x3 ac calendar to preload with android touch screen
- [x] annoying gradient on all calendar

**Comment by bigretromike** [comment]
```
8:18:48.204 T:2124   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 404: Not Found
                                            Traceback (most recent call last):
                                              File "C:\Users\brm\AppData\Roaming\Kodi\addons\script.module.nakamori\lib\windows\ac_calendar.py", line 144, in onAction
                                                body = json.loads(pyproxy.get_json(url))
                                              File "C:\Users\brm\AppData\Roaming\Kodi\addons\script.module.nakamori-lib\lib\proxy\python_version_proxy.py", line 280, in get_json
                                                raise err
                                            HTTPError: HTTP Error 404: Not Found
                                            -->End of Python script error report<--
18:18:54.460 T:2124   ERROR: Previous line repeats 1 times.
18:18:54.460 T:2124   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: argument 1 must be string, not None
                                            Traceback (most recent call last):
                                              File "C:\Users\brm\AppData\Roaming\Kodi\addons\script.module.nakamori\lib\windows\ac_calendar.py", line 159, in onAction
                                                xbmc.executebuiltin(script_utils.series_info(aid=aid), True)
                                            TypeError: argument 1 must be string, not None
                                            -->End of Python script error report<--
```

**Comment by bigretromike** [comment]
extra move_down
```
18:41:09.185 T:2972  NOTICE: Found method: Player.OnStop
18:41:09.395 T:3632  NOTICE: Nakamori|nakamori_player::finished_episode#L62 -> Video current_time (1334.1060791) has passed watch mark (1088.25). Marking is as watched!
18:41:09.673 T:3632  NOTICE: Nakamori|nakamori_player::player_loop#L212 -> Playback Ended - Shutting Down: 0
18:41:09.735 T:3632  NOTICE: Nakamori|nakamori_player::player_loop#L215 -> post-finish: start events
18:41:09.819 T:3740  NOTICE: CVideoPlayer::CloseFile()
18:41:09.819 T:3740  NOTICE: VideoPlayer: waiting for threads to exit
18:41:09.819 T:3740  NOTICE: VideoPlayer: finished waiting
18:41:09.819 T:3740  NOTICE: CVideoPlayer::CloseFile()
18:41:09.819 T:3740  NOTICE: VideoPlayer: waiting for threads to exit
18:41:09.819 T:3740  NOTICE: VideoPlayer: finished waiting
18:41:10.107 T:2972  NOTICE: onNotification
18:41:10.107 T:2972  NOTICE: Found data: {"id":-1,"type":"episode"}
18:41:10.107 T:2972  NOTICE: Found method: VideoLibrary.OnUpdate
18:41:10.107 T:2972  NOTICE: Found response: {u'type': u'episode', u'id': -1}
18:41:15.657 T:3596  NOTICE:  move_position_on_list : 10
18:41:33.525 T:3740  NOTICE: Previous line repeats 1 times.
```

**Comment by bigretromike** [comment]
```
2019-08-21 22:39:21.003 T:22354   ERROR: EXCEPTION: Unknown addon id 'script.module.nakamori-lib'.
2019-08-21 22:39:21.012 T:22354   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: Unknown addon id 'script.module.nakamori-lib'.
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.nakamori/nakamoriscript.py", line 3, in <module>
                                                import debug
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.nakamori-lib/lib/debug.py", line 5, in <module>
                                                from nakamori_utils.globalvars import *
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.nakamori-lib/lib/nakamori_utils/globalvars.py", line 20, in <module>
                                                lib_addon = xbmcaddon.Addon('script.module.nakamori-lib')
                                            RuntimeError: Unknown addon id 'script.module.nakamori-lib'.
                                            -->End of Python script error report<--
2019-08-21 22:39:21.226 T:22316   ERROR: Delete - Error deleting file /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/packages/metadata.tvshows.themoviedb.org-3.1.3.zip
2019-08-21 22:39:21.226 T:22316   ERROR: Delete - Error deleting file special://home/addons/packages/metadata.tvshows.themoviedb.org-3.1.3.zip
```

**Comment by bigretromike** [comment]
```

ERROR: Control 50 in window 10025 has been asked to focus, but it can't
2019-08-21 22:44:31.297 T:22680 WARNING: Attempt to use invalid handle -1
```
