### ISSUE TITLE
Nakamori 4.0 No longer working after playing first file.

### ISSUE THREAD

**Issue by Kristijan1001** [bigretromike/nakamori#469]
I can't access the all category or recently added series. Can still see and open other groups. Reinstall doesn't help its permanently broken. It is probably linked with something from ShokoServer. It says to check logs for error, but where can I find the logs ?

It also shows error occurred immediately once kodi is launched. 

Found it:

```
2021-11-06 09:15:59.721 T:16800   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
                                                   Traceback (most recent call last):
                                                     File "C:\ko\Kodi\portable_data\addons\plugin.video.nakamori\nakamoriplugin.py", line 509, in <module>
                                                       plugin.run()
                                                     File "C:\ko\Kodi\portable_data\addons\script.module.routing\lib\routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "C:\ko\Kodi\portable_data\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "C:\ko\Kodi\portable_data\addons\plugin.video.nakamori\nakamoriplugin.py", line 90, in list_groups_by_filter_id
                                                       y = kodi_models.list_all_groups_by_filter_id(filter_id)
                                                     File "C:\ko\Kodi\portable_data\addons\plugin.video.nakamori\models\kodi_models.py", line 864, in list_all_groups_by_filter_id
                                                       list_of_listitems.append((g.id, ThisType.group, get_listitem_from_group(g)))
                                                     File "C:\ko\Kodi\portable_data\addons\plugin.video.nakamori\models\kodi_models.py", line 140, in get_listitem_from_group
                                                       set_rating(li, rate_type='anidb', rate_value=float(x.rating), votes=int(x.votes), default=True)
                                                   TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
                                                   -->End of Python script error report<--
```

**Comment by Kristijan1001** [comment]
Downloaded Master from the Git instead of the 4.0. Issue is gone.

**Comment by bigretromike** [comment]
@Kristijan1001 thanks for feedback. I did fixed few things recently. I'm still testing build until its go to stable repo ;-)
Glad that update fixed your issue;
