### ISSUE TITLE
PythonToCppException - thrown when clicking Category

### ISSUE THREAD

**Issue by SomeRandomDude870** [bigretromike/nakamori#507]
Hi, I hope that this is still being updated...

I get the above exception when I click on a Category. Like "all", or an self made group and quite often inside groups (like Tags) when I click on some of the Tags.

Kodi 19.3, newest Shoko Server

` WARNING <general>: CPythonInvoker(122, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
2022-05-06 19:46:53.201 T:12287    INFO <general>: Python interpreter stopped
2022-05-06 19:46:59.514 T:12327    INFO <general>: initializing python engine.
2022-05-06 19:47:00.612 T:12327   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'urllib.error.HTTPError'>
                                                   Error Contents: HTTP Error 500: Internal Server Error
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py", line 509, in <module>
                                                       plugin.run()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py", line 90, in list_groups_by_filter_id
                                                       y = kodi_models.list_all_groups_by_filter_id(filter_id)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/models/kodi_models.py", line 854, in list_all_groups_by_filter_id
                                                       x = api.filter(q)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/api/shoko/v2/api2.py", line 97, in filter
                                                       response = self.api_client.call(url='/api/filter', call_type=APIType.GET, query=opts.__dict__)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/api/common/__init__.py", line 161, in call
                                                       response = urlopen(req, timeout=int(self.timeout))
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
                                                       return opener.open(url, data, timeout)
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/urllib/request.py", line 531, in open
                                                       response = meth(req, response)
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/urllib/request.py", line 640, in http_response
                                                       response = self.parent.error(
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/urllib/request.py", line 569, in error
                                                       return self._call_chain(*args)
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
                                                       result = func(*args)
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default
                                                       raise HTTPError(req.full_url, code, msg, hdrs, fp)
                                                   urllib.error.HTTPError: HTTP Error 500: Internal Server Error
                                                   -->End of Python script error report<--`

**Comment by SomeRandomDude870** [comment]
Nakamori 4.0 and Shoko nightly.

**Comment by bigretromike** [comment]
https://github.com/bigretromike/nakamori/issues/508

Based on the log you posted, you are using it on Android. 
Are you using grouping series option in ShokoServer?
