### ISSUE TITLE
4.1 - Cannot open Addon

### ISSUE THREAD

**Issue by SomeRandomDude870** [bigretromike/nakamori#510]
HI, I wanted to provide more information for my last problem, but then I have seen that there is a new Version out and installed that one.
Before that I was at least able to open the first Site and some Subsites.

When I now click on nakamori Addon, I will just get an Error Notification.

Kodi 19.4
Fire TV Stick 4k Max
Shoko Server Nightly
Nakamori 4.1

`  ERROR <general>: ERROR: EMBY.hooks.monitor: EmbyServer Connect error
2022-05-27 15:03:59.187 T:6186    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'urllib.error.HTTPError'>
                                                   Error Contents: HTTP Error 400: Bad Request
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py", line 980, in <module>
                                                       plugin.run()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py", line 43, in list_all_filters
                                                       y = kodi_models.list_all_filters()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/models/kodi_models.py", line 938, in list_all_filters
                                                       x = apiv2.filter(q)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/api/shoko/v2/api2.py", line 101, in filter
                                                       response = self.api_client.call(url='/api/filter', call_type=APIType.GET, query=opts.__dict__)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/api/common/__init__.py", line 172, in call
                                                       response = urlopen(req, timeout=int(self.timeout))
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
                                                       return opener.open(url, data, timeout)
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/urllib/request.py", line 531, in open
                                                       response = meth(req, response)
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/urllib/request.py", line 640, in http_response
                                                       response = self.parent.error(
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/urllib/request.py", line 569, in error
                                                       return self._call_chain(*args)
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
                                                       result = func(*args)
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default
                                                       raise HTTPError(req.full_url, code, msg, hdrs, fp)
                                                   urllib.error.HTTPError: HTTP Error 400: Bad Request
                                                   -->End of Python script error report<--

ERROR: EMBY.hooks.monitor: EmbyServer Connect error
2022-05-27 15:15:19.342 T:6621    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py", line 972, in <module>
                                                       xbmc.log(f'======= {sys.argv[1]}', xbmc.LOGDEBUG)
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--
                                                   
2022-05-27 15:15:20.045 T:6621  WARNING <general>: CPythonInvoker(42, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
2022-05-27 15:15:20.046 T:6621     INFO <general>: Python interpreter stopped`

I believe the first error was when it still opened the first site and the 2nd when it doesn´t even do that.

**Comment by bigretromike** [comment]
ok, can you go into nakamori plugin settings and do both connection and login wizard;

**Comment by SomeRandomDude870** [comment]
lol no, I can´t open the Addon at all.
When I check in Configure of Kodi then the correct data is filled.... although if I click at "restore defaults", the "Advanced" setting will not be deleted.

Now I get this after the long Error:
And yes, I already restarted the Stick multiple times.

`2022-05-27 15:50:07.753 T:8150  WARNING <general>: CPythonInvoker(96, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
2022-05-27 15:50:07.754 T:8150     INFO <general>: Python interpreter stopped
2022-05-27 15:50:07.763 T:8149    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.nakamori/
2022-05-27 15:50:07.774 T:7018    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.nakamori/) failed
2022-05-27 15:50:09.553 T:8154     INFO <general>: initializing python engine.`

**Comment by bigretromike** [comment]
> lol no, I can´t open the Addon at all. When I check in Configure of Kodi then the correct data is filled.... although if I click at "restore defaults", the "Advanced" setting will not be deleted.
> 
> Now I get this after the long Error: And yes, I already restarted the Stick multiple times.
> 
> `2022-05-27 15:50:07.753 T:8150 WARNING <general>: CPythonInvoker(96, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE 2022-05-27 15:50:07.754 T:8150 INFO <general>: Python interpreter stopped 2022-05-27 15:50:07.763 T:8149 ERROR <general>: GetDirectory - Error getting plugin://plugin.video.nakamori/ 2022-05-27 15:50:07.774 T:7018 ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.nakamori/) failed 2022-05-27 15:50:09.553 T:8154 INFO <general>: initializing python engine.`

This error is because nakamori throw error and didn't exit properly. this don't give us any clue.

**Comment by da3dsoul** [comment]
You can edit addon settings without opening them. The location depends on the skin, but generally, you open the context menu on the add-on from the add-ons list

**Comment by bigretromike** [comment]
Hope you not using older, hacker `routing` plugin that was needed to use with Nakamori 3.x.x

**Comment by bigretromike** [comment]
> lol no, I can´t open the Addon at all. When I check in Configure of Kodi then the correct data is filled.... although if I click at "restore defaults", the "Advanced" setting will not be deleted.
> 
> Now I get this after the long Error: And yes, I already restarted the Stick multiple times.
> 
> `2022-05-27 15:50:07.753 T:8150 WARNING <general>: CPythonInvoker(96, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE 2022-05-27 15:50:07.754 T:8150 INFO <general>: Python interpreter stopped 2022-05-27 15:50:07.763 T:8149 ERROR <general>: GetDirectory - Error getting plugin://plugin.video.nakamori/ 2022-05-27 15:50:07.774 T:7018 ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.nakamori/) failed 2022-05-27 15:50:09.553 T:8154 INFO <general>: initializing python engine.`

for my device, you need to click "default" and the "ok" so the settings are saved

**Comment by SomeRandomDude870** [comment]
Okay, sorry - UPDATE
I just did change the Genre Settings. I basically activated everything related to Genre to see what they do and then it throw me out. Not sure if it happened with the Last or when I was switching to Save.

Here:
`
 17:39:15.734 T:12297   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.nakamori/settings
2022-05-27 17:40:24.709 T:11180    INFO <general>: Loading skin file: DialogNumeric.xml, load type: KEEP_IN_MEMORY
2022-05-27 17:40:27.174 T:11180 WARNING <general>: CGUIWindowManager - HandleAction - ignoring action 7, because topmost modal dialog closing animation is running
2022-05-27 17:40:44.549 T:11180   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.nakamori/settings) failed
2022-05-27 17:40:44.562 T:12327    INFO <general>: initializing python engine.

.......

17:41:25.517 T:12368    INFO <general>: initializing python engine.
2022-05-27 17:41:26.283 T:12364    INFO <general>: CPythonInvoker(113, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autocompletion/plugin.py): script successfully run
2022-05-27 17:41:27.235 T:12364    INFO <general>: Python interpreter stopped
2022-05-27 17:41:27.956 T:12367    INFO <general>: CPythonInvoker(114, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autocompletion/plugin.py): script successfully run
2022-05-27 17:41:28.782 T:12367    INFO <general>: Python interpreter stopped
2022-05-27 17:41:29.208 T:12368    INFO <general>: CPythonInvoker(115, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autocompletion/plugin.py): script successfully run
2022-05-27 17:41:29.964 T:12368    INFO <general>: Python interpreter stopped
2022-05-27 17:41:34.611 T:12374    INFO <general>: initializing python engine.
2022-05-27 17:41:36.023 T:12374    INFO <general>: CPythonInvoker(116, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py): script successfully run
2022-05-27 17:41:36.790 T:12374 WARNING <general>: CPythonInvoker(116, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
2022-05-27 17:41:36.790 T:12374    INFO <general>: Python interpreter stopped
2022-05-27 17:41:39.131 T:12378    INFO <general>: initializing python engine.
2022-05-27 17:41:40.187 T:12378    INFO <general>: CPythonInvoker(117, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py): script successfully run
2022-05-27 17:41:40.942 T:12378 WARNING <general>: CPythonInvoker(117, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
2022-05-27 17:41:40.942 T:12378    INFO <general>: Python interpreter stopped
2022-05-27 17:41:40.953 T:12377   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.nakamori/settings
2022-05-27 17:43:45.348 T:11188    INFO <general>: CActiveAESink::OpenSink - initialize sink
2022-05-27 17:43:45.348 T:11188    INFO <general>: Trying to open: samplerate: 44100, channelMask: 12, encoding: 4
2022-05-27 17:43:45.354 T:11188    INFO <general>: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 56720 m_frames: 1418 m_frameSize: 8 channels: 2
2022-05-27 17:44:15.774 T:11180   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.nakamori/settings) failed
2022-05-27 17:44:15.782 T:12420    INFO <general>: initializing python engine.
2022-05-27 17:44:16.908 T:12420   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'urllib.error.HTTPError'>
                                                   Error Contents: HTTP Error 400: Bad Request
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py", line 980, in <module>
                                                       plugin.run()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py", line 43, in list_all_filters
                                                       y = kodi_models.list_all_filters()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/models/kodi_models.py", line 938, in list_all_filters
                                                       x = apiv2.filter(q)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/api/shoko/v2/api2.py", line 101, in filter
                                                       response = self.api_client.call(url='/api/filter', call_type=APIType.GET, query=opts.__dict__)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/api/common/__init__.py", line 172, in call
                                                       response = urlopen(req, timeout=int(self.timeout))
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
                                                       return opener.open(url, data, timeout)
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/urllib/request.py", line 531, in open
                                                       response = meth(req, response)
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/urllib/request.py", line 640, in http_response
                                                       response = self.parent.error(
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/urllib/request.py", line 569, in error
                                                       return self._call_chain(*args)
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
                                                       result = func(*args)
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default
                                                       raise HTTPError(req.full_url, code, msg, hdrs, fp)
                                                   urllib.error.HTTPError: HTTP Error 400: Bad Request
                                                   -->End of Python script error report<--
                                                   
2022-05-27 17:44:17.706 T:12420 WARNING <general>: CPythonInvoker(118, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
2022-05-27 17:44:17.707 T:12420    INFO <general>: Python interpreter stopped
2022-05-27 17:44:17.713 T:12418   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.nakamori/
2022-05-27 17:44:17.731 T:11180   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.nakamori/) failed
2022-05-27 17:44:21.932 T:12419   ERROR <general>: DoWork - Direct texture file loading failed for androidapp://sources/apps/com.amazon.metricstest.png
2022-05-27 17:44:22.019 T:12417   ERROR <general>: DoWork - Direct texture file loading failed for androidapp://sources/apps/com.android.documentsui.png
2022-05-27 17:44:23.687 T:11180   ERROR <general>: Control 50 in window 10025 has been asked to focus, but it can't
2022-05-27 17:44:23.708 T:12429    INFO <general>: initializing python engine.
2022-05-27 17:44:24.941 T:12429   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'urllib.error.HTTPError'>
                                                   Error Contents: HTTP Error 400: Bad Request
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py", line 980, in <module>
                                                       plugin.run()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py", line 43, in list_all_filters
                                                       y = kodi_models.list_all_filters()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/models/kodi_models.py", line 938, in list_all_filters
                                                       x = apiv2.filter(q)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/api/shoko/v2/api2.py", line 101, in filter
                                                       response = self.api_client.call(url='/api/filter', call_type=APIType.GET, query=opts.__dict__)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/api/common/__init__.py", line 172, in call
                                                       response = urlopen(req, timeout=int(self.timeout))
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
                                                       return opener.open(url, data, timeout)
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/urllib/request.py", line 531, in open
                                                       response = meth(req, response)
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/urllib/request.py", line 640, in http_response
                                                       response = self.parent.error(
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/urllib/request.py", line 569, in error
                                                       return self._call_chain(*args)
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
                                                       result = func(*args)
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default
                                                       raise HTTPError(req.full_url, code, msg, hdrs, fp)
                                                   urllib.error.HTTPError: HTTP Error 400: Bad Request
                                                   -->End of Python script error report<--
                                                   
2022-05-27 17:44:25.716 T:12429 WARNING <general>: CPythonInvoker(119, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
2022-05-27 17:44:25.716 T:12429    INFO <general>: Python interpreter stopped
2022-05-27 17:44:25.722 T:12428   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.nakamori/
2022-05-27 17:44:25.727 T:11180   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.nakamori/) failed`




10 minutes before that I also got this one:... didn´t even see that there was an problem.

`17:33:29.897 T:12129    INFO <general>: == process_month == 2022/6/1 : already = ['2022-05-28', '2022-05-30'] - url=https://raw.githubusercontent.com/bigretromike/anime-offline-calendar/master/seasons/%s-%02d.json 
2022-05-27 17:33:29.951 T:12129   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'NameError'>
                                                   Error Contents: name 'ImageFont' is not defined
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/lib/windows/ac_calendar.py", line 166, in onInit
                                                       self.AddSeriesToCalendar()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/lib/windows/ac_calendar.py", line 139, in AddSeriesToCalendar
                                                       if self.process_series_json(series):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/lib/windows/ac_calendar.py", line 400, in process_series_json
                                                       font = ImageFont.truetype(this_path, int(font_size), encoding='unic')
                                                   NameError: name 'ImageFont' is not defined
                                                   -->End of Python script error report<--
                                                   
2022-05-27 17:33:32.014 T:11180   ERROR <general>: Control 51 in window 10025 has been asked to focus, but it can't
2022-05-27 17:33:32.025 T:12129    INFO <general>: CPythonInvoker(91, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py): script successfully run
2022-05-27 17:33:32.056 T:12132    INFO <general>: initializing python engine.
2022-05-27 17:33:32.791 T:12129 WARNING <general>: CPythonInvoker(91, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
2022-05-27 17:33:32.791 T:12129    INFO <general>: Python interpreter stopped
2022-05-27 17:33:32.803 T:12128   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.nakamori/calendar`

**Comment by bigretromike** [comment]
The later part is related to issue I found out with calendar and missing library on Android Kodi build. 

@SomeRandomDude870 I understand `I just did change the Genre Settings.` your are refering to `Tag FIlter` in Nakamori settings or some kind of settings in shoko server?

**Comment by bigretromike** [comment]
There was and issue with ShokoServer and `Inverted` flag (aka `Show` in Nakamori). 
I pushed patch for the issue, should be up and running with newest daily build that will include it.
