### ISSUE TITLE
PIL/Pillow throw error on Android device for Calendar

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#512]
```
2022-05-27 17:33:29.951 T:12129 ERROR : EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'NameError'>
Error Contents: name 'ImageFont' is not defined
Traceback (most recent call last):
File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/lib/windows/ac_calendar.py", line 166, in onInit
self.AddSeriesToCalendar()
File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/lib/windows/ac_calendar.py", line 139, in AddSeriesToCalendar
if self.process_series_json(series):
File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nakamori/lib/windows/ac_calendar.py", line 400, in process_series_json
font = ImageFont.truetype(this_path, int(font_size), encoding='unic')
NameError: name 'ImageFont' is not defined
-->End of Python script error report<--
```

Make workaround using different text maker or use labels instead of images

**Comment by bigretromike** [comment]
` <import addon="script.module.pil" version="1.1.7"/>`

https://github.com/xbmc/xbmc/issues/21531
