### ISSUE TITLE
User ratings can also be non-integer numbers

### ISSUE THREAD

**Issue by SamuelBMartins** [bigretromike/nakamori#515]
I recently installed Nakamori and every time i try to open the list of all the anime it gives me an error. 

Here the logs:
```
2022-08-13 13:29:54.510 T:956     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
   Error Type: <class 'ValueError'>
   Error Contents: invalid literal for int() with base 10: '8.5'
   Traceback (most recent call last):
     File "/storage/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py", line 987, in <module>
       plugin.run(argv)
     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
       self._dispatch(self.path)
     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
       view_func(**kwargs)
     File "/storage/.kodi/addons/plugin.video.nakamori/nakamoriplugin.py", line 90, in list_groups_by_filter_id
       y = kodi_models.list_all_groups_by_filter_id(filter_id)
     File "/storage/.kodi/addons/plugin.video.nakamori/models/kodi_models.py", line 999, in list_all_groups_by_filter_id
       list_of_listitems.append((g.series[0].id, ThisType.series, get_listitem_from_serie(g.series[0])))
     File "/storage/.kodi/addons/plugin.video.nakamori/models/kodi_models.py", line 106, in get_listitem_from_serie
       set_info_for_series(li, x, was_watched, forced_title)
     File "/storage/.kodi/addons/plugin.video.nakamori/models/kodi_models.py", line 666, in set_info_for_series
       video['userrating'] = int(x.userrating)
   ValueError: invalid literal for int() with base 10: '8.5'
   -->End of Python script error report<--
```

I rated an anime 8.5 using Shoko Desktop. I think the problem is here:
https://github.com/bigretromike/nakamori/blob/db1478f73ac0eeb58b0c6c2191135141e2072abf/models/kodi_models.py#L666

**Comment by bigretromike** [comment]
yes, and no.
One should not score non integer (ex. decimal) rating, because its not support by anidb.

I will fix this as soon I get some extra free time.

Also please consider using valid rating if you want to contribute your scorring to AniDb.

**Comment by bigretromike** [comment]
Thanks you for reporting issue;
The issue has been resolved, sorry for the trouble.
